"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app
"""

from setuptools import setup

APP = ['SmolPlayer.py']
DATA_FILES = ['assets', 'songlist.txt', 'urllist.txt']
OPTIONS = {
    'iconfile':'app.icns',
    'plist': {
            'CFBundleName': "SmolPlayer.app",
            'CFBundleDisplayName': "SmolPlayer.app",
            'CFBundleGetInfoString': "Youtube Audio Player",
            'CFBundleIdentifier': "com.42.osx.smolplayer",
            'CFBundleVersion': "1.0.42",
            'CFBundleShortVersionString': "0.1.42",
            'NSHumanReadableCopyright': u"Copyright © 2020, Noah Broyles, All Rights Reserved"
        }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'], install_requires=['requests', 'beautifulsoup4', 'python-vlc', 'pafy']
)
