"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app
"""

from setuptools import setup

APP = ['SmolPlayer.py']
DATA_FILES = ['assets', 'songlist.txt', 'urllist.txt']
OPTIONS = {'iconfile':'app.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'], install_requires=['requests', 'beautifulsoup4', 'python-vlc', 'pafy']
)
